server:
  port: 80
  servlet:
    context-path: /ir

spring:
  redis:
    database: 0
    host: 172.16.85.140
    port: 6379
    password: 1234
    timeout: 10000ms  # 超时时间
    lettuce:
      pool:
        max-idle: 8 # 最大空闲连接数，默认值为8
        max-wait: -1ms # 最大连接阻塞等待时间，默认值-1
        min-idle: 2 # 最小空闲连接数
        max-active: 20 #最大连接数

